# Inspired from https://github.com/PhotonVision/photon-pi-gen/blob/master/config
name: build-docker

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    # required to run on this specific version of Ubuntu
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: APT update
      run: |
        sudo apt update
        sudo apt install binfmt-support
        sudo apt install qemu qemu-user-static
        sudo update-binfmts --enable

    # Build image with docker
    - name: Run build-docker.sh
      run: ./build-docker.sh

    # Print output directory files
    - name: List output files
      run: ls -lh deploy

    - name: Upload built image
      uses: actions/upload-artifact@v4
      with:
        name: built-image
        path: ./deploy/image_*presentium-full.zip
        if-no-files-found: error

    - name: Upload debug artifacts
      uses: actions/upload-artifact@v4
      with:
        name: debug-files
        path: | 
          ./deploy/*presentium-full.info
          ./deploy/build.log
        if-no-files-found: error
  
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: built-image
      - uses: softprops/action-gh-release@v1
        with:
          files: '**/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
